=== Darkhouse13/VerveQ/schemas/award_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Player Award",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "Season": {
        "type": "string"
      },
      "Player": {
        "type": "string"
      },
      "Nation": {
        "type": "string"
      },
      "Age": {
        "type": "string"
      },
      "Squad": {
        "type": "string"
      },
      "Pos": {
        "type": "string"
      }
    },
    "required": ["Season", "Player", "Nation", "Age", "Squad", "Pos"]
  }
}

=== Darkhouse13/VerveQ/data/Ballon_d_Or.json
[{"Season":"2024","Player":"Rodri","Nation":"ESP","Age":"27","Squad":"Spain, Manchester City","Pos":"MF"},{"Season":"2023","Player":"Lionel Messi","Nation":"ARG","Age":"35","Squad":"Argentina, Inter Miami, Paris Saint-Germain","Pos":"FW"},{"Season":"2022","Player":"Karim Benzema","Nation":"FRA","Age":"34","Squad":"France, Real Madrid","Pos":"FW"},{"Season":"2021","Player":"Lionel Messi","Nation":"ARG","Age":"33","Squad":"Argentina, Barcelona","Pos":"FW,MF"},{"Season":"2019","Player":"Lionel Messi","Nation":"ARG","Age":"31","Squad":"Argentina, Barcelona","Pos":"FW"},{"Season":"2018","Player":"Luka Modrić","Nation":"CRO","Age":"32","Squad":"Croatia, Real Madrid","Pos":"MF"},{"Season":"2017","Player":"Cristiano Ronaldo","Nation":"POR","Age":"31","Squad":"Portugal, Real Madrid","Pos":"FW"},{"Season":"2016","Player":"Cristiano Ronaldo","Nation":"POR","Age":"30","Squad":"Portugal, Real Madrid","Pos":"FW"},{"Season":"2015","Player":"Lionel Messi","Nation":"ARG","Age":"27","Squad":"Argentina, Barcelona","Pos":"FW,MF"},{"Season":"2014","Player":"Cristiano Ronaldo","Nation":"POR","Age":"28","Squad":"Portugal, Real Madrid","Pos":"FW,MF"},{"Season":"2013","Player":"Cristiano Ronaldo","Nation":"POR","Age":"27","Squad":"Real Madrid","Pos":"FW,MF"},{"Season":"2012","Player":"Lionel Messi","Nation":"ARG","Age":"24","Squad":"Barcelona","Pos":"FW,MF"},{"Season":"2011","Player":"Lionel Messi","Nation":"ARG","Age":"23","Squad":"Barcelona","Pos":"FW,MF"},{"Season":"2010","Player":"Lionel Messi","Nation":"ARG","Age":"22","Squad":"Argentina, Barcelona","Pos":"FW,MF"},{"Season":"2009","Player":"Lionel Messi","Nation":"ARG","Age":"21","Squad":"Barcelona","Pos":"FW,MF"},{"Season":"2008","Player":"Cristiano Ronaldo","Nation":"POR","Age":"22","Squad":"Portugal, Manchester United","Pos":"FW,MF"},{"Season":"2007","Player":"Kaká","Nation":"BRA","Age":"24","Squad":"Milan","Pos":"FW,MF"},{"Season":"2006","Player":"Fabio Cannavaro","Nation":"ITA","Age":"32","Squad":"Italy, Juventus","Pos":"DF"},{"Season":"2005","Player":"Ronaldinho","Nation":"BRA","Age":"24","Squad":"Brazil, Barcelona","Pos":"MF,FW"},{"Season":"2004","Player":"Andriy Shevchenko","Nation":"UKR","Age":"27","Squad":"Milan","Pos":"FW"},{"Season":"2003","Player":"Pavel Nedvěd","Nation":"CZE","Age":"30","Squad":"Juventus","Pos":"MF"},{"Season":"2002","Player":"Ronaldo","Nation":"BRA","Age":"25","Squad":"Brazil, Internazionale","Pos":"FW"},{"Season":"2001","Player":"Michael Owen","Nation":"ENG","Age":"21","Squad":"Liverpool","Pos":"FW"},{"Season":"2000","Player":"Luís Figo","Nation":"POR","Age":"27","Squad":"Portugal,Barcelona","Pos":"FW,MF"},{"Season":"1999","Player":"Rivaldo","Nation":"BRA","Age":"26","Squad":"Barcelona","Pos":"FW,MF"},{"Season":"1998","Player":"Zinédine Zidane","Nation":"FRA","Age":"25","Squad":"France, Juventus","Pos":"MF"},{"Season":"1997","Player":"Ronaldo","Nation":"BRA","Age":"20","Squad":"Barcelona","Pos":"FW"},{"Season":"1996","Player":"Matthias Sammer","Nation":"GER","Age":"28","Squad":"Dortmund","Pos":"DF,MF"},{"Season":"1995","Player":"George Weah","Nation":"LBR","Age":"28","Squad":"Paris Saint-Germain","Pos":"FW"},{"Season":"1994","Player":"Hristo Stoichkov","Nation":"BUL","Age":"27","Squad":"Bulgaria, Barcelona","Pos":"FW,MF"},{"Season":"1993","Player":"Roberto Baggio","Nation":"ITA","Age":"25","Squad":"Juventus","Pos":"FW,MF"},{"Season":"1992","Player":"Marco van Basten","Nation":"NED","Age":"27","Squad":"Milan","Pos":"FW"},{"Season":"1991","Player":"Jean-Pierre Papin","Nation":"FRA","Age":"27","Squad":"Marseille","Pos":"FW"},{"Season":"1990","Player":"LothMatthäus","Nation":"GER","Age":"28","Squad":"Germany, Internazionale","Pos":"DF,MF"},{"Season":"1989","Player":"Marco van Basten","Nation":"NED","Age":"24","Squad":"Milan","Pos":"FW"},{"Season":"1988","Player":"Marco van Basten","Nation":"NED","Age":"23","Squad":"Netherlands, Milan","Pos":"FW"},{"Season":"1987","Player":"Ruud Gullit","Nation":"NED","Age":"24","Squad":"Netherlands, Milan","Pos":"FW,MF"},{"Season":"1986","Player":"Igor Belanov","Nation":"URS","Age":"25","Squad":"Soviet Union","Pos":"FW,MF"},{"Season":"1985","Player":"Michel Platini","Nation":"FRA","Age":"29","Squad":"France, Juventus","Pos":"MF"},{"Season":"1984","Player":"Michel Platini","Nation":"FRA","Age":"28","Squad":"France, Juventus","Pos":"MF"},{"Season":"1983","Player":"Michel Platini","Nation":"FRA","Age":"27","Squad":"France, Juventus","Pos":"MF"},{"Season":"1982","Player":"Paolo Rossi","Nation":"ITA","Age":"25","Squad":"Italy","Pos":"FW"},{"Season":"1981","Player":"Karl-Heinz Rummenigge","Nation":"GER","Age":"25","Squad":"Germany, Bayern Munich","Pos":"FW"},{"Season":"1980","Player":"Karl-Heinz Rummenigge","Nation":"GER","Age":"24","Squad":"Germany, Bayern Munich","Pos":"FW"},{"Season":"1979","Player":"Kevin Keegan","Nation":"ENG","Age":"27","Squad":"England, Hamburg","Pos":"FW"},{"Season":"1978","Player":"Kevin Keegan","Nation":"ENG","Age":"26","Squad":"England, Hamburg","Pos":"FW"},{"Season":"1977","Player":"Allan Simonsen","Nation":"DEN","Age":"24","Squad":"Denmark, Borussia Monchengladbach","Pos":"FW"},{"Season":"1976","Player":"Franz Beckenbauer","Nation":"GER","Age":"30","Squad":"Germany, Bayern Munich","Pos":"DF,MF"},{"Season":"1975","Player":"Oleh Blokhin","Nation":"URS","Age":"22","Squad":"Soviet Union, Dynamo Kyiv","Pos":"FW"},{"Season":"1974","Player":"Johan Cruyff","Nation":"NED","Age":"26","Squad":"Netherlands","Pos":"FW,MF"},{"Season":"1973","Player":"Johan Cruyff","Nation":"NED","Age":"25","Squad":"Netherlands, Ajax","Pos":"FW,MF"},{"Season":"1972","Player":"Franz Beckenbauer","Nation":"GER","Age":"26","Squad":"Germany, Bayern Munich","Pos":"DF,MF"},{"Season":"1971","Player":"Johan Cruyff","Nation":"NED","Age":"23","Squad":"Netherlands, Ajax","Pos":"FW,MF"},{"Season":"1970","Player":"Gerd Müller","Nation":"GER","Age":"24","Squad":"Germany","Pos":"FW"},{"Season":"1969","Player":"Gianni Rivera","Nation":"ITA","Age":"25","Squad":"Italy, Milan","Pos":"FW,MF"},{"Season":"1968","Player":"George Best","Nation":"NIR","Age":"21","Squad":"Northern Ireland, Manchester United","Pos":"FW,MF"},{"Season":"1967","Player":"Flórián Albert","Nation":"HUN","Age":"25","Squad":"Hungary, Ferencvaros","Pos":"FW"},{"Season":"1966","Player":"Bobby Charlton","Nation":"ENG","Age":"28","Squad":"England","Pos":"FW,MF"},{"Season":"1965","Player":"Eusébio","Nation":"POR","Age":"23","Squad":"Portugal, Benfica","Pos":"FW"},{"Season":"1964","Player":"Denis Law","Nation":"SCO","Age":"23","Squad":"Scotland, Manchester United","Pos":"FW"},{"Season":"1963","Player":"Lev Yashin","Nation":"URS","Age":"33","Squad":"Soviet Union, Dynamo Moscow","Pos":"GK"},{"Season":"1962","Player":"Josef Masopust","Nation":"TCH","Age":"30","Squad":"Czechoslovakia","Pos":"MF"},{"Season":"1961","Player":"OmSívori","Nation":"ARG","Age":"25","Squad":"Italy, Juventus","Pos":"FW,MF"},{"Season":"1960","Player":"Luis Suárez","Nation":"ESP","Age":"24","Squad":"Spain, Barcelona","Pos":"MF"},{"Season":"1959","Player":"Alfredo Di Stéfano","Nation":"ARG","Age":"32","Squad":"Spain, Real Madrid","Pos":"FW"},{"Season":"1958","Player":"Raymond Kopa","Nation":"FRA","Age":"26","Squad":"France","Pos":"FW,MF"},{"Season":"1957","Player":"Alfredo Di Stéfano","Nation":"ARG","Age":"30","Squad":"Spain, Real Madrid","Pos":"FW"},{"Season":"1956","Player":"Stanley Matthews","Nation":"ENG","Age":"40","Squad":"England, Blackpool","Pos":"FW,MF"}]

=== Darkhouse13/VerveQ/data/SerieA_Footballer_of_the_Year.json
[{"Season":"2024","Player":"Lautaro Martínez","Nation":"ARG","Age":"26","Squad":"Argentina, Internazionale","Pos":"FW"},{"Season":"2023","Player":"Victor Osimhen","Nation":"NGA","Age":"24","Squad":"Nigeria, Napoli","Pos":"FW"},{"Season":"2022","Player":"Rafael Leão","Nation":"POR","Age":"22","Squad":"Portugal, Milan","Pos":"FW"},{"Season":"2021","Player":"Romelu Lukaku","Nation":"BEL","Age":"27","Squad":"Belgium, Chelsea, Internazionale","Pos":"FW"},{"Season":"2020","Player":"Cristiano Ronaldo","Nation":"POR","Age":"34","Squad":"Portugal, Juventus","Pos":"FW"},{"Season":"2019","Player":"Cristiano Ronaldo","Nation":"POR","Age":"33","Squad":"Portugal, Juventus","Pos":"FW"},{"Season":"2018","Player":"Mauro Icardi","Nation":"ARG","Age":"24","Squad":"Argentina, Internazionale","Pos":"FW"},{"Season":"2017","Player":"Gianluigi Buffon","Nation":"ITA","Age":"39","Squad":"Italy, Juventus","Pos":"GK"},{"Season":"2016","Player":"Leonardo Bonucci","Nation":"ITA","Age":"28","Squad":"Italy, Juventus","Pos":"DF"},{"Season":"2015","Player":"Carlos Tevez","Nation":"ARG","Age":"30","Squad":"Argentina, Boca Juniors, Juventus","Pos":"FW,MF"},{"Season":"2014","Player":"Andrea Pirlo","Nation":"ITA","Age":"34","Squad":"Italy, Juventus","Pos":"MF"},{"Season":"2013","Player":"Andrea Pirlo","Nation":"ITA","Age":"33","Squad":"Italy, Juventus","Pos":"MF"},{"Season":"2012","Player":"Zlatan Ibrahimović","Nation":"SWE","Age":"30","Squad":"Sweden, Milan","Pos":"FW"},{"Season":"2011","Player":"Diego Milito","Nation":"ARG","Age":"31","Squad":"Internazionale","Pos":"FW"},{"Season":"2010","Player":"Zlatan Ibrahimović","Nation":"SWE","Age":"28","Squad":"Sweden, Barcelona","Pos":"FW"},{"Season":"2009","Player":"Zlatan Ibrahimović","Nation":"SWE","Age":"27","Squad":"Internazionale","Pos":"FW"},{"Season":"2008","Player":"Kaká","Nation":"BRA","Age":"25","Squad":"Milan","Pos":"FW,MF"},{"Season":"2007","Player":"Fabio Cannavaro","Nation":"ITA","Age":"33","Squad":"Real Madrid","Pos":"DF"},{"Season":"2006","Player":"Alberto Gilardino","Nation":"ITA","Age":"23","Squad":"Italy, Milan","Pos":"FW"},{"Season":"2005","Player":"Kaká","Nation":"BRA","Age":"22","Squad":"Brazil, Milan","Pos":"MF"},{"Season":"2004","Player":"Francesco Totti","Nation":"ITA","Age":"27","Squad":"Italy, Roma","Pos":"FW,MF"},{"Season":"2003","Player":"Pavel Nedvěd","Nation":"CZE","Age":"30","Squad":"Juventus","Pos":"MF"},{"Season":"2002","Player":"David Trezeguet","Nation":"FRA","Age":"24","Squad":"France, Juventus","Pos":"FW"},{"Season":"2001","Player":"Zinédine Zidane","Nation":"FRA","Age":"28","Squad":"Juventus","Pos":"MF"},{"Season":"2000","Player":"Francesco Totti","Nation":"ITA","Age":"23","Squad":"Italy, Roma","Pos":"FW,MF"},{"Season":"1999","Player":"Christian Vieri","Nation":"ITA","Age":"25","Squad":"Lazio","Pos":"FW"},{"Season":"1998","Player":"Ronaldo","Nation":"BRA","Age":"21","Squad":"Brazil, Internazionale","Pos":"FW"},{"Season":"1997","Player":"Roberto Mancini","Nation":"ITA","Age":"32","Squad":"Sampdoria","Pos":"FW"}]

=== Darkhouse13/VerveQ/data/LaLiga_Best_Player.json
[{"Season":"2024-2025","Player":"Raphinha","Nation":"BRA","Age":"27","Squad":"Barcelona","Pos":"FW,MF"},{"Season":"2023-2024","Player":"JuBellingham","Nation":"ENG","Age":"20","Squad":"Real Madrid","Pos":"MF,FW"},{"Season":"2022-2023","Player":"Marc-André ter Stegen","Nation":"GER","Age":"30","Squad":"Germany, Barcelona","Pos":"GK"},{"Season":"2021-2022","Player":"Karim Benzema","Nation":"FRA","Age":"33","Squad":"Real Madrid","Pos":"FW"},{"Season":"2020-2021","Player":"Jan Oblak","Nation":"SVN","Age":"27","Squad":"Slovenia, Atlético Madrid","Pos":"GK"},{"Season":"2019-2020","Player":"Karim Benzema","Nation":"FRA","Age":"31","Squad":"Real Madrid","Pos":"FW"},{"Season":"2018-2019","Player":"Lionel Messi","Nation":"ARG","Age":"31","Squad":"Barcelona","Pos":"FW"},{"Season":"2017-2018","Player":"Lionel Messi","Nation":"ARG","Age":"30","Squad":"Barcelona","Pos":"FW"},{"Season":"2016-2017","Player":"Lionel Messi","Nation":"ARG","Age":"29","Squad":"Barcelona","Pos":"FW,MF"},{"Season":"2015-2016","Player":"Antoine Griezmann","Nation":"FRA","Age":"24","Squad":"Atlético Madrid","Pos":"FW,MF"},{"Season":"2014-2015","Player":"Lionel Messi","Nation":"ARG","Age":"27","Squad":"Barcelona","Pos":"FW,MF"},{"Season":"2013-2014","Player":"Cristiano Ronaldo","Nation":"POR","Age":"28","Squad":"Real Madrid","Pos":"FW,MF"},{"Season":"2012-2013","Player":"Lionel Messi","Nation":"ARG","Age":"25","Squad":"Barcelona","Pos":"FW,MF"},{"Season":"2011-2012","Player":"Lionel Messi","Nation":"ARG","Age":"24","Squad":"Barcelona","Pos":"FW,MF"},{"Season":"2010-2011","Player":"Lionel Messi","Nation":"ARG","Age":"23","Squad":"Barcelona","Pos":"FW,MF"},{"Season":"2009-2010","Player":"Lionel Messi","Nation":"ARG","Age":"22","Squad":"Barcelona","Pos":"FW,MF"},{"Season":"2008-2009","Player":"Lionel Messi","Nation":"ARG","Age":"21","Squad":"Barcelona","Pos":"FW,MF"}]

=== Darkhouse13/VerveQ/data/African_Footballer_of_the_Year.json
[{"Season":"2024","Player":"Ademola Lookman","Nation":"NGA","Age":"26","Squad":"Nigeria, Atalanta","Pos":"FW,MF"},{"Season":"2023","Player":"Victor Osimhen","Nation":"NGA","Age":"24","Squad":"Nigeria, Napoli","Pos":"FW"},{"Season":"2022","Player":"Sadio Mané","Nation":"SEN","Age":"29","Squad":"Senegal, Liverpool","Pos":"MF,FW"},{"Season":"2019","Player":"Sadio Mané","Nation":"SEN","Age":"26","Squad":"Senegal, Liverpool","Pos":"FW"},{"Season":"2018","Player":"Mohamed Salah","Nation":"EGY","Age":"25","Squad":"Egypt, Liverpool","Pos":"FW,MF"},{"Season":"2017","Player":"Mohamed Salah","Nation":"EGY","Age":"24","Squad":"Egypt, Roma","Pos":"FW,MF"},{"Season":"2016","Player":"Riyad Mahrez","Nation":"ALG","Age":"24","Squad":"Leicester City","Pos":"FW,MF"},{"Season":"2015","Player":"Pierre-Emerick Aubameyang","Nation":"GAB","Age":"25","Squad":"Gabon, Dortmund","Pos":"FW,MF"},{"Season":"2015","Player":"Yaya Touré","Nation":"CIV","Age":"31","Squad":"Côte d'Ivoire, Manchester City","Pos":"MF"},{"Season":"2014","Player":"Yaya Touré","Nation":"CIV","Age":"30","Squad":"Côte d'Ivoire, Manchester City","Pos":"MF"},{"Season":"2013","Player":"Yaya Touré","Nation":"CIV","Age":"29","Squad":"Côte d'Ivoire, Manchester City","Pos":"MF"},{"Season":"2012","Player":"Yaya Touré","Nation":"CIV","Age":"28","Squad":"Côte d'Ivoire, Manchester City","Pos":"MF"},{"Season":"2010","Player":"Samuel Eto'o","Nation":"CMR","Age":"28","Squad":"Cameroon, Internazionale","Pos":"FW"},{"Season":"2009","Player":"Didier Drogba","Nation":"CIV","Age":"30","Squad":"Chelsea","Pos":"FW"},{"Season":"2008","Player":"Emmanuel Adebayor","Nation":"TOG","Age":"23","Squad":"Arsenal","Pos":"FW"},{"Season":"2007","Player":"Frédéric Kanouté","Nation":"MLI","Age":"29","Squad":"Sevilla","Pos":"FW"},{"Season":"2006","Player":"Didier Drogba","Nation":"CIV","Age":"27","Squad":"Côte d'Ivoire, Chelsea","Pos":"FW"},{"Season":"2005","Player":"Samuel Eto'o","Nation":"CMR","Age":"23","Squad":"Barcelona","Pos":"FW"},{"Season":"2004","Player":"Samuel Eto'o","Nation":"CMR","Age":"22","Squad":"Mallorca","Pos":"FW"},{"Season":"2003","Player":"Samuel Eto'o","Nation":"CMR","Age":"21","Squad":"Cameroon, Mallorca","Pos":"FW"},{"Season":"2002","Player":"El Hadji Diouf","Nation":"SEN","Age":"21","Squad":"Senegal, Lens","Pos":"FW,MF"},{"Season":"2001","Player":"El Hadji Diouf","Nation":"SEN","Age":"20","Squad":"Lens","Pos":"FW,MF"},{"Season":"2000","Player":"Patrick M'Boma","Nation":"CMR","Age":"29","Squad":"Cagliari","Pos":"FW"},{"Season":"1999","Player":"Nwankwo Kanu","Nation":"NGA","Age":"22","Squad":"Arsenal, Internazionale","Pos":"FW"},{"Season":"1998","Player":"Mustapha Hadji","Nation":"MAR","Age":"26","Squad":"Morocco, SportiCP, Deportivo La Coruña","Pos":"MF"},{"Season":"1997","Player":"Victor Ikpeba","Nation":"NGA","Age":"23","Squad":"Monaco","Pos":"FW"},{"Season":"1996","Player":"Nwankwo Kanu","Nation":"NGA","Age":"19","Squad":"Ajax","Pos":"FW"},{"Season":"1995","Player":"George Weah","Nation":"LBR","Age":"28","Squad":"Paris Saint-Germain","Pos":"FW"},{"Season":"1994","Player":"Emmanuel Amunike","Nation":"NGA","Age":"23","Squad":"Nigeria","Pos":"FW,MF"},{"Season":"1993","Player":"Rashidi Yekini","Nation":"NGA","Age":"29","Squad":"Vitória de Setúbal","Pos":"FW"},{"Season":"1992","Player":"Abedi Pele","Nation":"GHA","Age":"27","Squad":"Marseille","Pos":"FW,MF"},{"Season":"1991","Player":"Abedi Pele","Nation":"GHA","Age":"26","Squad":"Marseille","Pos":"FW,MF"},{"Season":"1990","Player":"Roger Milla","Nation":"CMR","Age":"37","Squad":"Cameroon","Pos":"FW"},{"Season":"1989","Player":"George Weah","Nation":"LBR","Age":"22","Squad":"Monaco","Pos":"FW"},{"Season":"1988","Player":"Kalusha Bwalya","Nation":"ZAM","Age":"24","Squad":"Cercle Brugge","Pos":"FW,MF"},{"Season":"1987","Player":"Rabah Madjer","Nation":"ALG","Age":"28","Squad":"Porto","Pos":"FW"},{"Season":"1986","Player":"Ezzaki Badou","Nation":"MAR","Age":"26","Squad":"Morocco","Pos":"GK"},{"Season":"1985","Player":"Mohamed Timoumi","Nation":"MAR","Age":"25","Squad":"AS FAR","Pos":"FW,MF"},{"Season":"1984","Player":"Théophile Abega","Nation":"CMR","Age":"29","Squad":"Toulouse","Pos":"MF"},{"Season":"1983","Player":"Mahmoud El Khatib","Nation":"EGY","Age":"28","Squad":"Al Ahly","Pos":"FW,MF"},{"Season":"1982","Player":"Thomas N'Kono","Nation":"CMR","Age":"26","Squad":"Cameroon","Pos":"GK"},{"Season":"1981","Player":"Lakhdar Belloumi","Nation":"ALG","Age":"22","Squad":"GC Mascara","Pos":"MF"},{"Season":"1980","Player":"Jean ManOnguéné","Nation":"CMR","Age":"33","Squad":"Canon Yadoundé","Pos":"FW"},{"Season":"1979","Player":"Thomas N'Kono","Nation":"CMR","Age":"23","Squad":"Canon Yadoundé","Pos":"GK"},{"Season":"1978","Player":"Karim Abdul Razak","Nation":"GHA","Age":"21","Squad":"Asante Kotoko","Pos":"MF"},{"Season":"1977","Player":"Tarak Dhiab","Nation":"TUN","Age":"22","Squad":"Espérance Tunis","Pos":"MF"},{"Season":"1976","Player":"Roger Milla","Nation":"CMR","Age":"23","Squad":"Tonnerre Yaoundé","Pos":"FW"},{"Season":"1975","Player":"Ahmed Faras","Nation":"MAR","Age":"29","Squad":"Mohammédia","Pos":"FW,MF"},{"Season":"1974","Player":"Paul Moukila","Nation":"CGO","Age":"23","Squad":"CARA Brazzaville","Pos":"FW,MF"},{"Season":"1973","Player":"BwanTshimen","Nation":"COD","Age":"24","Squad":"TP Mazembe","Pos":"DF,MF"},{"Season":"1972","Player":"Chérif Souleymane","Nation":"GUI","Age":"28","Squad":"Hafia","Pos":"MF"},{"Season":"1971","Player":"Ibrahim Sunday","Nation":"GHA","Age":"26","Squad":"Asante Kotoko","Pos":"MF"},{"Season":"1970","Player":"Salif Keïta","Nation":"MLI","Age":"23","Squad":"Saint-Étienne","Pos":"FW"}]

=== Darkhouse13/VerveQ/data/PL_Player_of_the_Season.json
[{"Season":"2023-2024","Player":"Phil Foden","Nation":"ENG","Age":"23","Squad":"Manchester City","Pos":"FW,MF"},{"Season":"2022-2023","Player":"Erling Haaland","Nation":"NOR","Age":"22","Squad":"Norway, Manchester City","Pos":"FW"},{"Season":"2021-2022","Player":"Kevin De Bruyne","Nation":"BEL","Age":"30","Squad":"Manchester City","Pos":"MF"},{"Season":"2020-2021","Player":"Rúben Dias","Nation":"POR","Age":"23","Squad":"Portugal, Manchester City, Benfica","Pos":"DF"},{"Season":"2019-2020","Player":"Kevin De Bruyne","Nation":"BEL","Age":"28","Squad":"Manchester City","Pos":"MF,FW"},{"Season":"2018-2019","Player":"Virgil van Dijk","Nation":"NED","Age":"27","Squad":"Netherlands, Liverpool","Pos":"DF"},{"Season":"2017-2018","Player":"Mohamed Salah","Nation":"EGY","Age":"25","Squad":"Liverpool","Pos":"FW"},{"Season":"2016-2017","Player":"N'Golo Kanté","Nation":"FRA","Age":"25","Squad":"Chelsea","Pos":"MF"},{"Season":"2015-2016","Player":"Jamie Vardy","Nation":"ENG","Age":"28","Squad":"Leicester City","Pos":"FW"},{"Season":"2014-2015","Player":"Eden Hazard","Nation":"BEL","Age":"23","Squad":"Chelsea","Pos":"FW,MF"},{"Season":"2013-2014","Player":"Luis Suárez","Nation":"URU","Age":"26","Squad":"Liverpool","Pos":"FW"},{"Season":"2012-2013","Player":"Gareth Bale","Nation":"WAL","Age":"23","Squad":"Tottenham Hotspur","Pos":"FW,MF"},{"Season":"2011-2012","Player":"Vincent Kompany","Nation":"BEL","Age":"25","Squad":"Manchester City","Pos":"DF"},{"Season":"2010-2011","Player":"Nemanja Vidić","Nation":"SRB","Age":"28","Squad":"Manchester United","Pos":"DF"},{"Season":"2009-2010","Player":"Wayne Rooney","Nation":"ENG","Age":"23","Squad":"Manchester United","Pos":"FW,MF"},{"Season":"2008-2009","Player":"Nemanja Vidić","Nation":"SRB","Age":"26","Squad":"Manchester United","Pos":"DF"},{"Season":"2007-2008","Player":"Cristiano Ronaldo","Nation":"POR","Age":"22","Squad":"Manchester United","Pos":"FW,MF"},{"Season":"2006-2007","Player":"Cristiano Ronaldo","Nation":"POR","Age":"21","Squad":"Manchester United","Pos":"FW,MF"},{"Season":"2005-2006","Player":"Thierry Henry","Nation":"FRA","Age":"27","Squad":"Arsenal","Pos":"FW"},{"Season":"2004-2005","Player":"Frank Lampard","Nation":"ENG","Age":"26","Squad":"Chelsea","Pos":"MF"},{"Season":"2003-2004","Player":"Thierry Henry","Nation":"FRA","Age":"25","Squad":"Arsenal","Pos":"FW"},{"Season":"2002-2003","Player":"Ruud van Nistelrooy","Nation":"NED","Age":"26","Squad":"Manchester United","Pos":"FW"},{"Season":"2001-2002","Player":"Freddie Ljungberg","Nation":"SWE","Age":"24","Squad":"Arsenal","Pos":"FW,MF"},{"Season":"2000-2001","Player":"Patrick Vieira","Nation":"FRA","Age":"24","Squad":"Arsenal","Pos":"MF"},{"Season":"1999-2000","Player":"Kevin Phillips","Nation":"ENG","Age":"26","Squad":"Sunderland","Pos":"FW"},{"Season":"1998-1999","Player":"Dwight Yorke","Nation":"TRI","Age":"26","Squad":"Aston Villa, Manchester United","Pos":"FW,MF"},{"Season":"1997-1998","Player":"Michael Owen","Nation":"ENG","Age":"17","Squad":"Liverpool","Pos":"FW"},{"Season":"1996-1997","Player":"Juninho Paulista","Nation":"BRA","Age":"23","Squad":"Middlesbrough","Pos":"MF"},{"Season":"1995-1996","Player":"Peter Schmeichel","Nation":"DEN","Age":"31","Squad":"Manchester United","Pos":"GK"},{"Season":"1994-1995","Player":"Alan Shearer","Nation":"ENG","Age":"23","Squad":"Blackburn Rovers","Pos":"FW"}]

=== Darkhouse13/VerveQ/data/L1_Player_of_the_Year.json
[{"Season":"2024-2025","Player":"Ousmane Dembélé","Nation":"FRA","Age":"27","Squad":"France, Paris Saint-Germain","Pos":"MF,FW"},{"Season":"2023-2024","Player":"Kylian Mbappé","Nation":"FRA","Age":"24","Squad":"Paris Saint-Germain","Pos":"FW"},{"Season":"2022-2023","Player":"Kylian Mbappé","Nation":"FRA","Age":"23","Squad":"France, Paris Saint-Germain","Pos":"FW"},{"Season":"2021-2022","Player":"Kylian Mbappé","Nation":"FRA","Age":"22","Squad":"Paris Saint-Germain","Pos":"FW"},{"Season":"2020-2021","Player":"Kylian Mbappé","Nation":"FRA","Age":"21","Squad":"France, Paris Saint-Germain","Pos":"FW"},{"Season":"2018-2019","Player":"Kylian Mbappé","Nation":"FRA","Age":"19","Squad":"France, Paris Saint-Germain","Pos":"MF"},{"Season":"2017-2018","Player":"Neymar","Nation":"BRA","Age":"25","Squad":"Paris Saint-Germain","Pos":"FW"},{"Season":"2016-2017","Player":"Edinson Cavani","Nation":"URU","Age":"29","Squad":"Paris Saint-Germain","Pos":"FW,MF"},{"Season":"2015-2016","Player":"Zlatan Ibrahimović","Nation":"SWE","Age":"33","Squad":"Paris Saint-Germain","Pos":"FW"},{"Season":"2014-2015","Player":"Alexandre Lacazette","Nation":"FRA","Age":"23","Squad":"Lyon","Pos":"FW"},{"Season":"2013-2014","Player":"Zlatan Ibrahimović","Nation":"SWE","Age":"31","Squad":"Paris Saint-Germain","Pos":"FW"},{"Season":"2012-2013","Player":"Zlatan Ibrahimović","Nation":"SWE","Age":"30","Squad":"Paris Saint-Germain","Pos":"FW"},{"Season":"2011-2012","Player":"Eden Hazard","Nation":"BEL","Age":"20","Squad":"Lille","Pos":"FW,MF"},{"Season":"2010-2011","Player":"Eden Hazard","Nation":"BEL","Age":"19","Squad":"Lille","Pos":"FW,MF"},{"Season":"2009-2010","Player":"Lisandro López","Nation":"ARG","Age":"26","Squad":"Lyon","Pos":"FW,MF"},{"Season":"2008-2009","Player":"Yoann Gourcuff","Nation":"FRA","Age":"22","Squad":"Bordeaux","Pos":"MF"},{"Season":"2007-2008","Player":"Karim Benzema","Nation":"FRA","Age":"19","Squad":"Lyon","Pos":"FW"},{"Season":"2006-2007","Player":"Florent Malouda","Nation":"FRA","Age":"26","Squad":"Lyon","Pos":"FW,MF"},{"Season":"2005-2006","Player":"Juninho Pernambucano","Nation":"BRA","Age":"30","Squad":"Lyon","Pos":"MF"},{"Season":"2004-2005","Player":"Michael Essien","Nation":"GHA","Age":"21","Squad":"Lyon","Pos":"DF,MF"},{"Season":"2003-2004","Player":"Didier Drogba","Nation":"CIV","Age":"25","Squad":"Marseille","Pos":"FW"},{"Season":"2002-2003","Player":"Pauleta","Nation":"POR","Age":"29","Squad":"Bordeaux","Pos":"FW"},{"Season":"2001-2002","Player":"Pauleta","Nation":"POR","Age":"28","Squad":"Bordeaux","Pos":"FW"},{"Season":"2000-2001","Player":"Éric Carrière","Nation":"FRA","Age":"27","Squad":"Nantes","Pos":"MF"},{"Season":"1999-2000","Player":"Marcelo Gallardo","Nation":"ARG","Age":"23","Squad":"Monaco","Pos":"MF"},{"Season":"1998-1999","Player":"Ali Benarbia","Nation":"ALG","Age":"29","Squad":"Bordeaux","Pos":"MF"},{"Season":"1997-1998","Player":"Marco Simone","Nation":"ITA","Age":"28","Squad":"Paris Saint-Germain","Pos":"FW,MF"},{"Season":"1996-1997","Player":"Sonny Anderson","Nation":"BRA","Age":"25","Squad":"Monaco","Pos":"FW"},{"Season":"1995-1996","Player":"Zinédine Zidane","Nation":"FRA","Age":"23","Squad":"Bordeaux","Pos":"MF"},{"Season":"1994-1995","Player":"Vincent Guérin","Nation":"FRA","Age":"28","Squad":"Paris Saint-Germain","Pos":"MF"},{"Season":"1993-1994","Player":"David Ginola","Nation":"FRA","Age":"26","Squad":"France, Paris Saint-Germain","Pos":"FW,MF"}]

=== Darkhouse13/VerveQ/data/Bundesliga_Top_Scorers.json
[
    {
        "Season": "2023-2024",
        "Player": "Harry Kane",
        "Nation": "ENG",
        "Age": "30",
        "Squad": "Bayern Munich",
        "Pos": "FW"
    },
    {
        "Season": "2022-2023",
        "Player": "Niclas Füllkrug",
        "Nation": "GER",
        "Age": "29",
        "Squad": "Werder Bremen",
        "Pos": "FW"
    },
    {
        "Season": "2021-2022",
        "Player": "Robert Lewandowski",
        "Nation": "POL",
        "Age": "33",
        "Squad": "Bayern Munich",
        "Pos": "FW"
    }
]
