=== Darkhouse13/VerveQ/schemas/player_stats_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Player Stats",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "stat_name": {
        "type": "string"
      },
      "player_name": {
        "type": "string"
      },
      "team_name": {
        "type": "string"
      },
      "stat_value": {
        "type": "string"
      }
    },
    "required": ["stat_name", "player_name", "team_name", "stat_value"]
  }
}

=== Darkhouse13/VerveQ/data/LaLiga_Players_Stats.json
[{"stat_name":"Goals/90","player_name":"Alexander Sørloth","team_name":"Atlético Madrid","stat_value":" 1.15"},{"stat_name":"Assists","player_name":"Lamine Yamal","team_name":"Barcelona","stat_value":" 13"},{"stat_name":"Assists/90","player_name":"Isco","team_name":"Betis","stat_value":" 0.47"},{"stat_name":"Goals + Assists","player_name":"Kylian Mbappé","team_name":"Real Madrid","stat_value":" 34"},{"stat_name":"Goals + Assists/90","player_name":"Alexander Sørloth","team_name":"Atlético Madrid","stat_value":" 1.26"},{"stat_name":"Penalty Kicks Made","player_name":"Ante Budimir","team_name":"Osasuna","stat_value":" 8"},{"stat_name":"Non-Penalty Goals","player_name":"Kylian Mbappé","team_name":"Real Madrid","stat_value":" 24"},{"stat_name":"Non-Penalty Goals/90","player_name":"Alexander Sørloth","team_name":"Atlético Madrid","stat_value":" 1.09"},{"stat_name":"Non-Penalty Goals + Assists/90","player_name":"Alexander Sørloth","team_name":"Atlético Madrid","stat_value":" 1.21"},{"stat_name":"xG: Expected Goals","player_name":"Robert Lewandowski","team_name":"Barcelona","stat_value":" 27.1"},{"stat_name":"xG/90","player_name":"Alexander Sørloth","team_name":"Atlético Madrid","stat_value":" 0.97"},{"stat_name":"npxG: Non-Penalty xG","player_name":"Robert Lewandowski","team_name":"Barcelona","stat_value":" 24.0"},{"stat_name":"npxG/90","player_name":"Alexander Sørloth","team_name":"Atlético Madrid","stat_value":" 0.92"},{"stat_name":"xAG: Exp. Assisted Goals","player_name":"Lamine Yamal","team_name":"Barcelona","stat_value":" 13.9"},{"stat_name":"xAG/90","player_name":"Lamine Yamal","team_name":"Barcelona","stat_value":" 0.44"},{"stat_name":"Shots Total","player_name":"Kylian Mbappé","team_name":"Real Madrid","stat_value":" 152"},{"stat_name":"Shots Total/90","player_name":"Kylian Mbappé","team_name":"Real Madrid","stat_value":" 4.71"},{"stat_name":"Shots on Target","player_name":"Kylian Mbappé","team_name":"Real Madrid","stat_value":" 75"},{"stat_name":"Shots on target/90","player_name":"Kylian Mbappé","team_name":"Real Madrid","stat_value":" 2.32"},{"stat_name":"Shots on Target %","player_name":"Borja Iglesias","team_name":"Celta Vigo","stat_value":" 60.9"},{"stat_name":"Goals/Shot","player_name":"Roberto Férnandez","team_name":"Espanyol","stat_value":" 0.29"},{"stat_name":"Goals/Shot on Target","player_name":"Daniel Vivian","team_name":"Athletic Club","stat_value":" 0.80"},{"stat_name":"npxG/Shot","player_name":"Orri Steinn Óskarsson","team_name":"Real Sociedad","stat_value":" 0.27"},{"stat_name":"Goals - xG","player_name":"Ayoze Pérez","team_name":"Villarreal","stat_value":" +6.3"},{"stat_name":"Non-Penalty Goals - npxG","player_name":"Ayoze Pérez","team_name":"Villarreal","stat_value":" +6.3"},{"stat_name":"Key Passes","player_name":"Alex Baena","team_name":"Villarreal","stat_value":" 95"},{"stat_name":"Pass Completion %","player_name":"Frenkie de Jong","team_name":"Barcelona","stat_value":" 94.4"},{"stat_name":"Progressive Passing Distance","player_name":"Sergio Herrera","team_name":"Osasuna","stat_value":" 23382"},{"stat_name":"Passes into Final Third","player_name":"Pedri","team_name":"Barcelona","stat_value":" 331"},{"stat_name":"Passes into Penalty Area","player_name":"Lamine Yamal","team_name":"Barcelona","stat_value":" 95"},{"stat_name":"Crosses into Penalty Area","player_name":"Johan Mojica","team_name":"Mallorca","stat_value":" 33"},{"stat_name":"Progressive Passes","player_name":"Pedri","team_name":"Barcelona","stat_value":" 360"},{"stat_name":"Through Balls","player_name":"Lamine Yamal","team_name":"Barcelona","stat_value":" 33"},{"stat_name":"xA: Expected Assists","player_name":"Alex Baena","team_name":"Villarreal","stat_value":" 12.6"},{"stat_name":"xA/90","player_name":"Alex Baena","team_name":"Villarreal","stat_value":" 0.44"},{"stat_name":"Corner Kicks","player_name":"Raphinha","team_name":"Barcelona","stat_value":" 140"},{"stat_name":"Crosses","player_name":"Carlos Vicente","team_name":"Alavés","stat_value":" 269"},{"stat_name":"Throw-ins Taken","player_name":"Diego Rico","team_name":"Getafe","stat_value":" 399"},{"stat_name":"Shot-Creating Actions","player_name":"Lamine Yamal","team_name":"Barcelona","stat_value":" 188"},{"stat_name":"Shot-Creating Actions/90","player_name":"Isco","team_name":"Betis","stat_value":" 6.46"},{"stat_name":"Goal-Creating Actions","player_name":"Lamine Yamal","team_name":"Barcelona","stat_value":" 29"},{"stat_name":"Goal-Creating Actions/90","player_name":"Lamine Yamal","team_name":"Barcelona","stat_value":" 0.91"},{"stat_name":"Tackles","player_name":"Omar El Hilali","team_name":"Espanyol","stat_value":" 111"},{"stat_name":"Tackles Won","player_name":"Omar El Hilali","team_name":"Espanyol","stat_value":" 79"},{"stat_name":"Dribblers Tackled","player_name":"Jon Aramburu","team_name":"Real Sociedad","stat_value":" 66"},{"stat_name":"% of Dribblers Tackled","player_name":"Natan","team_name":"Betis","stat_value":" 86.7"},{"stat_name":"Blocks","player_name":"Renato Tapia","team_name":"Leganés","stat_value":" 58"},{"stat_name":"Interceptions","player_name":"Carmona","team_name":"Sevilla","stat_value":" 68"},{"stat_name":"Clearances","player_name":"Omar Alderete","team_name":"Getafe","stat_value":" 241"},{"stat_name":"Touches","player_name":"Pedri","team_name":"Barcelona","stat_value":" 3060"},{"stat_name":"Successful Take-Ons","player_name":"Lamine Yamal","team_name":"Barcelona","stat_value":" 161"},{"stat_name":"Successful Take-On %","player_name":"Loïc Bade","team_name":"Sevilla","stat_value":" 77.3"},{"stat_name":"Progressive Carrying Distance","player_name":"Iñigo Martínez","team_name":"Barcelona","stat_value":" 7336"},{"stat_name":"Progressive Carries","player_name":"Lamine Yamal","team_name":"Barcelona","stat_value":" 181"},{"stat_name":"Carries into Penalty Area","player_name":"Vinicius Júnior","team_name":"Real Madrid","stat_value":" 106"},{"stat_name":"Progressive Passes Rec","player_name":"Lamine Yamal","team_name":"Barcelona","stat_value":" 433"},{"stat_name":"Minutes","player_name":"Joan García","team_name":"Espanyol","stat_value":" 3420"},{"stat_name":"Substitute Appearances","player_name":"Ángel Correa","team_name":"Atlético Madrid","stat_value":" 28"},{"stat_name":"Points per Match","player_name":"Wojciech Szczęsny","team_name":"Barcelona","stat_value":" 2.87"},{"stat_name":"Plus/Minus","player_name":"Lamine Yamal","team_name":"Barcelona","stat_value":" +64"},{"stat_name":"Plus/Minus/90","player_name":"Dani Olmo","team_name":"Barcelona","stat_value":" +2.23"},{"stat_name":"xG Plus/Minus","player_name":"Lamine Yamal","team_name":"Barcelona","stat_value":" +49.3"},{"stat_name":"xG Plus/Minus/90","player_name":"Eric García","team_name":"Barcelona","stat_value":" +1.60"},{"stat_name":"Yellow Cards","player_name":"Yvan Neyou","team_name":"Leganés","stat_value":" 14"},{"stat_name":"Red Cards","player_name":"Mario Martín","team_name":"Valladolid","stat_value":" 3"},{"stat_name":"Aerials Won","player_name":"Lucas Torró","team_name":"Osasuna","stat_value":" 159"},{"stat_name":"% of Aerials Won","player_name":"Jon Martin","team_name":"Real Sociedad","stat_value":" 85.5"},{"stat_name":"Fouls Committed","player_name":"Lucas Torró","team_name":"Osasuna","stat_value":" 75"},{"stat_name":"Fouls Drawn","player_name":"Takefusa Kubo","team_name":"Real Sociedad","stat_value":" 73"},{"stat_name":"Own Goals","player_name":"Álex Suárez","team_name":"Las Palmas","stat_value":" 2"},{"stat_name":"Clean Sheets","player_name":"Jan Oblak","team_name":"Atlético Madrid","stat_value":" 15"},{"stat_name":"Clean Sheet Percentage","player_name":"Wojciech Szczęsny","team_name":"Barcelona","stat_value":" 53.3"},{"stat_name":"Saves","player_name":"Joan García","team_name":"Espanyol","stat_value":" 140"},{"stat_name":"Save Percentage","player_name":"Unai Simón","team_name":"Athletic Club","stat_value":" 79.0"},{"stat_name":"Goals Against/90","player_name":"Unai Simón","team_name":"Athletic Club","stat_value":" 0.67"},{"stat_name":"PSxG-GA","player_name":"Joan García","team_name":"Espanyol","stat_value":" +6.7"},{"stat_name":"PSxG-GA/90","player_name":"Joan García","team_name":"Espanyol","stat_value":" +0.18"}]

=== Darkhouse13/VerveQ/data/PL_Players_Stats.json
[{"stat_name":"Goals","player_name":"Mohamed Salah","team_name":"Liverpool","stat_value":" 29"},{"stat_name":"Goals/90","player_name":"Mohamed Salah","team_name":"Liverpool","stat_value":" 0.77"},{"stat_name":"Assists","player_name":"Mohamed Salah","team_name":"Liverpool","stat_value":" 18"},{"stat_name":"Assists/90","player_name":"Bukayo Saka","team_name":"Arsenal","stat_value":" 0.52"},{"stat_name":"Goals + Assists","player_name":"Mohamed Salah","team_name":"Liverpool","stat_value":" 47"},{"stat_name":"Goals + Assists/90","player_name":"Mohamed Salah","team_name":"Liverpool","stat_value":" 1.25"},{"stat_name":"Penalty Kicks Made","player_name":"Mohamed Salah","team_name":"Liverpool","stat_value":" 9"},{"stat_name":"Non-Penalty Goals","player_name":"Mohamed Salah","team_name":"Liverpool","stat_value":" 20"},{"stat_name":"Non-Penalty Goals/90","player_name":"Erling Haaland","team_name":"Manchester City","stat_value":" 0.62"},{"stat_name":"Non-Penalty Goals + Assists/90","player_name":"Mohamed Salah","team_name":"Liverpool","stat_value":" 1.01"},{"stat_name":"xG: Expected Goals","player_name":"Mohamed Salah","team_name":"Liverpool","stat_value":" 25.2"},{"stat_name":"xG/90","player_name":"Erling Haaland","team_name":"Manchester City","stat_value":" 0.72"},{"stat_name":"npxG: Non-Penalty xG","player_name":"Erling Haaland","team_name":"Manchester City","stat_value":" 18.8"},{"stat_name":"npxG/90","player_name":"Erling Haaland","team_name":"Manchester City","stat_value":" 0.62"},{"stat_name":"xAG: Exp. Assisted Goals","player_name":"Mohamed Salah","team_name":"Liverpool","stat_value":" 14.2"},{"stat_name":"xAG/90","player_name":"Kevin De Bruyne","team_name":"Manchester City","stat_value":" 0.42"},{"stat_name":"Shots Total","player_name":"Antoine Semenyo","team_name":"Bournemouth","stat_value":" 125"},{"stat_name":"Shots Total/90","player_name":"Julio Enciso","team_name":"","stat_value":" 4.02"},{"stat_name":"Shots on Target","player_name":"Erling Haaland","team_name":"Manchester City","stat_value":" 55"},{"stat_name":"Shots on target/90","player_name":"Erling Haaland","team_name":"Manchester City","stat_value":" 1.81"},{"stat_name":"Shots on Target %","player_name":"Jørgen Strand Larsen","team_name":"Wolves","stat_value":" 61.1"},{"stat_name":"Goals/Shot","player_name":"Jack Hinshelwood","team_name":"Brighton","stat_value":" 0.28"},{"stat_name":"Goals/Shot on Target","player_name":"Nikola Milenković","team_name":"Nott'ham Forest","stat_value":" 0.63"},{"stat_name":"npxG/Shot","player_name":"Richarlison","team_name":"Tottenham","stat_value":" 0.22"},{"stat_name":"Goals - xG","player_name":"Bryan Mbeumo","team_name":"Brentford","stat_value":" +7.7"},{"stat_name":"Non-Penalty Goals - npxG","player_name":"Bryan Mbeumo","team_name":"Brentford","stat_value":" +7.5"},{"stat_name":"Key Passes","player_name":"Bruno Fernandes","team_name":"Manchester Utd","stat_value":" 91"},{"stat_name":"Pass Completion %","player_name":"William Saliba","team_name":"Arsenal","stat_value":" 94.3"},{"stat_name":"Progressive Passing Distance","player_name":"Mark Flekken","team_name":"Brentford","stat_value":" 25308"},{"stat_name":"Passes into Final Third","player_name":"Virgil van Dijk","team_name":"Liverpool","stat_value":" 290"},{"stat_name":"Passes into Penalty Area","player_name":"Mohamed Salah","team_name":"Liverpool","stat_value":" 93"},{"stat_name":"Crosses into Penalty Area","player_name":"Antonee Robinson","team_name":"Fulham","stat_value":" 29"},{"stat_name":"Progressive Passes","player_name":"Bruno Fernandes","team_name":"Manchester Utd","stat_value":" 325"},{"stat_name":"Through Balls","player_name":"Bruno Fernandes","team_name":"Manchester Utd","stat_value":" 31"},{"stat_name":"xA: Expected Assists","player_name":"Bryan Mbeumo","team_name":"Brentford","stat_value":" 9.3"},{"stat_name":"xA/90","player_name":"Bukayo Saka","team_name":"Arsenal","stat_value":" 0.41"},{"stat_name":"Corner Kicks","player_name":"Andreas Pereira","team_name":"Fulham","stat_value":" 109"},{"stat_name":"Crosses","player_name":"Bryan Mbeumo","team_name":"Brentford","stat_value":" 202"},{"stat_name":"Throw-ins Taken","player_name":"Milos Kerkez","team_name":"Bournemouth","stat_value":" 279"},{"stat_name":"Shot-Creating Actions","player_name":"Cole Palmer","team_name":"Chelsea","stat_value":" 202"},{"stat_name":"Shot-Creating Actions/90","player_name":"Bukayo Saka","team_name":"Arsenal","stat_value":" 6.09"},{"stat_name":"Goal-Creating Actions","player_name":"Mohamed Salah","team_name":"Liverpool","stat_value":" 27"},{"stat_name":"Goal-Creating Actions/90","player_name":"Bukayo Saka","team_name":"Arsenal","stat_value":" 1.20"},{"stat_name":"Tackles","player_name":"Idrissa Gana Gueye","team_name":"Everton","stat_value":" 133"},{"stat_name":"Tackles Won","player_name":"Idrissa Gana Gueye","team_name":"Everton","stat_value":" 80"},{"stat_name":"Dribblers Tackled","player_name":"Noussair Mazraoui","team_name":"Manchester Utd","stat_value":" 59"},{"stat_name":"% of Dribblers Tackled","player_name":"Max Kilman","team_name":"West Ham","stat_value":" 85.2"},{"stat_name":"Blocks","player_name":"Nathan Collins","team_name":"Brentford","stat_value":" 77"},{"stat_name":"Interceptions","player_name":"Aaron Wan-Bissaka","team_name":"West Ham","stat_value":" 66"},{"stat_name":"Clearances","player_name":"Murillo","team_name":"Nott'ham Forest","stat_value":" 249"},{"stat_name":"Touches","player_name":"Virgil van Dijk","team_name":"Liverpool","stat_value":" 3301"},{"stat_name":"Successful Take-Ons","player_name":"Jeremy Doku","team_name":"Manchester City","stat_value":" 107"},{"stat_name":"Successful Take-On %","player_name":"Murillo","team_name":"Nott'ham Forest","stat_value":" 73.0"},{"stat_name":"Progressive Carrying Distance","player_name":"Jan Paul van Hecke","team_name":"Brighton","stat_value":" 7191"},{"stat_name":"Progressive Carries","player_name":"Jeremy Doku","team_name":"Manchester City","stat_value":" 213"},{"stat_name":"Carries into Penalty Area","player_name":"Mohamed Salah","team_name":"Liverpool","stat_value":" 126"},{"stat_name":"Progressive Passes Rec","player_name":"Mohamed Salah","team_name":"Liverpool","stat_value":" 488"},{"stat_name":"Minutes","player_name":"Bernd Leno","team_name":"Fulham","stat_value":" 3420"},{"stat_name":"Substitute Appearances","player_name":"Jack Taylor","team_name":"Ipswich Town","stat_value":" 28"},{"stat_name":"Points per Match","player_name":"Alexis Mac Allister","team_name":"Liverpool","stat_value":" 2.34"},{"stat_name":"Plus/Minus","player_name":"Luis Díaz","team_name":"Liverpool","stat_value":" +46"},{"stat_name":"Plus/Minus/90","player_name":"Luis Díaz","team_name":"Liverpool","stat_value":" +1.73"},{"stat_name":"xG Plus/Minus","player_name":"Virgil van Dijk","team_name":"Liverpool","stat_value":" +43.5"},{"stat_name":"xG Plus/Minus/90","player_name":"Trent Alexander-Arnold","team_name":"Liverpool","stat_value":" +1.40"},{"stat_name":"Yellow Cards","player_name":"Flynn Downes","team_name":"Southampton","stat_value":" 12"},{"stat_name":"Red Cards","player_name":"Jack Stephens","team_name":"Southampton","stat_value":" 2"},{"stat_name":"Aerials Won","player_name":"Dan Burn","team_name":"Newcastle Utd","stat_value":" 146"},{"stat_name":"% of Aerials Won","player_name":"James Tarkowski","team_name":"Everton","stat_value":" 75.6"},{"stat_name":"Fouls Committed","player_name":"Antoine Semenyo","team_name":"Bournemouth","stat_value":" 73"},{"stat_name":"Fouls Drawn","player_name":"Bruno Guimarães","team_name":"Newcastle Utd","stat_value":" 108"},{"stat_name":"Own Goals","player_name":"Marc Guéhi","team_name":"Crystal Palace","stat_value":" 3"},{"stat_name":"Clean Sheets","player_name":"Matz Sels","team_name":"Nott'ham Forest","stat_value":" 13"},{"stat_name":"Clean Sheet Percentage","player_name":"Ederson","team_name":"Manchester City","stat_value":" 38.5"},{"stat_name":"Saves","player_name":"Mark Flekken","team_name":"Brentford","stat_value":" 150"},{"stat_name":"Save Percentage","player_name":"Robert Sánchez","team_name":"Chelsea","stat_value":" 76.4"},{"stat_name":"Goals Against/90","player_name":"David Raya","team_name":"Arsenal","stat_value":" 0.89"},{"stat_name":"PSxG-GA","player_name":"Jordan Pickford","team_name":"Everton","stat_value":" +4.8"},{"stat_name":"PSxG-GA/90","player_name":"Ederson","team_name":"Manchester City","stat_value":" +0.16"}]
