=== Darkhouse13/VerveQ/schemas/squad_stats_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Squad Stats",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "squad": {
        "type": "string"
      },
      "num_players": {
        "type": "string"
      },
      "age": {
        "type": "string"
      },
      "poss": {
        "type": "string"
      },
      "gls": {
        "type": "string"
      },
      "ast": {
        "type": "string"
      },
      "np_gls": {
        "type": "string"
      },
      "p_gls": {
        "type": "string"
      },
      "p_att": {
        "type": "string"
      },
      "crd_y": {
        "type": "string"
      },
      "crd_r": {
        "type": "string"
      },
      "xG": {
        "type": "string"
      },
      "npxG": {
        "type": "string"
      },
      "xAG": {
        "type": "string"
      },
      "prgC": {
        "type": "string"
      },
      "prgP": {
        "type": "string"
      },
      "gls_per_game": {
        "type": "string"
      },
      "ast_per_game": {
        "type": "string"
      },
      "np_gls_per_game": {
        "type": "string"
      },
      "xG_per_game": {
        "type": "string"
      },
      "xAG_per_game": {
        "type": "string"
      },
      "npxG_per_game": {
        "type": "string"
      }
    },
    "required": [
      "squad",
      "num_players",
      "age",
      "poss",
      "gls",
      "ast",
      "np_gls",
      "p_gls",
      "p_att",
      "crd_y",
      "crd_r",
      "xG",
      "npxG",
      "xAG",
      "prgC",
      "prgP",
      "gls_per_game",
      "ast_per_game",
      "np_gls_per_game",
      "xG_per_game",
      "xAG_per_game",
      "npxG_per_game"
    ]
  }
}

=== Darkhouse13/VerveQ/data/La Liga_squad_std_stats.json
[{"squad":"Alavés","num_players":"29","age":"26.6","poss":"45.3","gls":"38","ast":"20","np_gls":"29","p_gls":"9","p_att":"11","crd_y":"107","crd_r":"5","xG":"42.8","npxG":"34.1","xAG":"25.4","prgC":"449","prgP":"1160","gls_per_game":"1.00","ast_per_game":"0.53","np_gls_per_game":"0.76","xG_per_game":"1.13","xAG_per_game":"0.67","npxG_per_game":"0.90"},{"squad":"Athletic Club","num_players":"31","age":"26.9","poss":"48.4","gls":"53","ast":"40","np_gls":"50","p_gls":"3","p_att":"6","crd_y":"64","crd_r":"3","xG":"53.0","npxG":"48.2","xAG":"36.7","prgC":"682","prgP":"1579","gls_per_game":"1.39","ast_per_game":"1.05","np_gls_per_game":"1.32","xG_per_game":"1.39","xAG_per_game":"0.97","npxG_per_game":"1.27"},{"squad":"Atlético Madrid","num_players":"24","age":"28.4","poss":"52.6","gls":"68","ast":"51","np_gls":"62","p_gls":"6","p_att":"7","crd_y":"75","crd_r":"3","xG":"64.6","npxG":"59.3","xAG":"47.9","prgC":"760","prgP":"1559","gls_per_game":"1.79","ast_per_game":"1.34","np_gls_per_game":"1.63","xG_per_game":"1.70","xAG_per_game":"1.26","npxG_per_game":"1.56"},{"squad":"Barcelona","num_players":"28","age":"24.7","poss":"68.3","gls":"99","ast":"72","np_gls":"92","p_gls":"7","p_att":"8","crd_y":"63","crd_r":"3","xG":"91.5","npxG":"85.2","xAG":"67.5","prgC":"860","prgP":"2212","gls_per_game":"2.61","ast_per_game":"1.89","np_gls_per_game":"2.42","xG_per_game":"2.41","xAG_per_game":"1.78","npxG_per_game":"2.24"},{"squad":"Betis","num_players":"36","age":"27.5","poss":"52.4","gls":"55","ast":"37","np_gls":"48","p_gls":"7","p_att":"10","crd_y":"75","crd_r":"4","xG":"54.7","npxG":"46.9","xAG":"37.5","prgC":"679","prgP":"1486","gls_per_game":"1.45","ast_per_game":"0.97","np_gls_per_game":"1.26","xG_per_game":"1.44","xAG_per_game":"0.99","npxG_per_game":"1.23"},{"squad":"Celta Vigo","num_players":"30","age":"26.9","poss":"53.6","gls":"58","ast":"40","np_gls":"50","p_gls":"8","p_att":"9","crd_y":"84","crd_r":"6","xG":"54.2","npxG":"47.3","xAG":"38.4","prgC":"709","prgP":"1659","gls_per_game":"1.53","ast_per_game":"1.05","np_gls_per_game":"1.32","xG_per_game":"1.43","xAG_per_game":"1.01","npxG_per_game":"1.24"},{"squad":"Espanyol","num_players":"27","age":"25.2","poss":"39.8","gls":"38","ast":"27","np_gls":"33","p_gls":"5","p_att":"5","crd_y":"88","crd_r":"1","xG":"34.4","npxG":"30.5","xAG":"24.5","prgC":"497","prgP":"1000","gls_per_game":"1.00","ast_per_game":"0.71","np_gls_per_game":"0.87","xG_per_game":"0.91","xAG_per_game":"0.65","npxG_per_game":"0.80"},{"squad":"Getafe","num_players":"30","age":"27.7","poss":"41.8","gls":"34","ast":"21","np_gls":"29","p_gls":"5","p_att":"5","crd_y":"110","crd_r":"7","xG":"36.8","npxG":"33.0","xAG":"23.9","prgC":"368","prgP":"981","gls_per_game":"0.89","ast_per_game":"0.55","np_gls_per_game":"0.76","xG_per_game":"0.97","xAG_per_game":"0.63","npxG_per_game":"0.87"},{"squad":"Girona","num_players":"30","age":"27.5","poss":"56.3","gls":"43","ast":"31","np_gls":"39","p_gls":"4","p_att":"5","crd_y":"76","crd_r":"2","xG":"42.5","npxG":"38.6","xAG":"31.6","prgC":"765","prgP":"1691","gls_per_game":"1.13","ast_per_game":"0.82","np_gls_per_game":"1.03","xG_per_game":"1.12","xAG_per_game":"0.83","npxG_per_game":"1.02"},{"squad":"Las Palmas","num_players":"34","age":"26.8","poss":"50.7","gls":"38","ast":"27","np_gls":"35","p_gls":"3","p_att":"4","crd_y":"110","crd_r":"4","xG":"36.3","npxG":"33.2","xAG":"26.3","prgC":"499","prgP":"1210","gls_per_game":"1.00","ast_per_game":"0.71","np_gls_per_game":"0.92","xG_per_game":"0.96","xAG_per_game":"0.69","npxG_per_game":"0.87"},{"squad":"Leganés","num_players":"26","age":"27.8","poss":"42.6","gls":"38","ast":"27","np_gls":"33","p_gls":"5","p_att":"7","crd_y":"82","crd_r":"6","xG":"36.0","npxG":"30.6","xAG":"23.3","prgC":"417","prgP":"1030","gls_per_game":"1.00","ast_per_game":"0.71","np_gls_per_game":"0.87","xG_per_game":"0.95","xAG_per_game":"0.61","npxG_per_game":"0.80"},{"squad":"Mallorca","num_players":"28","age":"28.7","poss":"46.8","gls":"34","ast":"24","np_gls":"30","p_gls":"4","p_att":"5","crd_y":"81","crd_r":"6","xG":"38.8","npxG":"34.9","xAG":"26.5","prgC":"479","prgP":"1184","gls_per_game":"0.89","ast_per_game":"0.63","np_gls_per_game":"0.79","xG_per_game":"1.02","xAG_per_game":"0.70","npxG_per_game":"0.92"},{"squad":"Osasuna","num_players":"25","age":"27.4","poss":"46.1","gls":"46","ast":"28","np_gls":"37","p_gls":"9","p_att":"9","crd_y":"88","crd_r":"0","xG":"44.0","npxG":"37.8","xAG":"29.8","prgC":"567","prgP":"1221","gls_per_game":"1.21","ast_per_game":"0.74","np_gls_per_game":"0.97","xG_per_game":"1.16","xAG_per_game":"0.78","npxG_per_game":"0.99"},{"squad":"Rayo Vallecano","num_players":"26","age":"29.3","poss":"51.7","gls":"38","ast":"27","np_gls":"38","p_gls":"0","p_att":"1","crd_y":"96","crd_r":"3","xG":"45.4","npxG":"44.6","xAG":"36.2","prgC":"589","prgP":"1362","gls_per_game":"1.00","ast_per_game":"0.71","np_gls_per_game":"1.00","xG_per_game":"1.20","xAG_per_game":"0.95","npxG_per_game":"1.17"},{"squad":"Real Madrid","num_players":"30","age":"26.6","poss":"60.4","gls":"78","ast":"55","np_gls":"68","p_gls":"10","p_att":"14","crd_y":"57","crd_r":"4","xG":"75.3","npxG":"64.5","xAG":"54.6","prgC":"983","prgP":"1967","gls_per_game":"2.05","ast_per_game":"1.45","np_gls_per_game":"1.79","xG_per_game":"1.98","xAG_per_game":"1.44","npxG_per_game":"1.70"},{"squad":"Real Sociedad","num_players":"31","age":"25.2","poss":"53.8","gls":"34","ast":"22","np_gls":"30","p_gls":"4","p_att":"4","crd_y":"85","crd_r":"4","xG":"42.5","npxG":"39.3","xAG":"30.9","prgC":"645","prgP":"1341","gls_per_game":"0.89","ast_per_game":"0.58","np_gls_per_game":"0.79","xG_per_game":"1.12","xAG_per_game":"0.81","npxG_per_game":"1.03"},{"squad":"Sevilla","num_players":"35","age":"26.1","poss":"50.5","gls":"39","ast":"32","np_gls":"37","p_gls":"2","p_att":"3","crd_y":"98","crd_r":"8","xG":"42.7","npxG":"40.3","xAG":"30.8","prgC":"594","prgP":"1193","gls_per_game":"1.03","ast_per_game":"0.84","np_gls_per_game":"0.97","xG_per_game":"1.12","xAG_per_game":"0.81","npxG_per_game":"1.06"},{"squad":"Valencia","num_players":"32","age":"24.7","poss":"48.4","gls":"43","ast":"26","np_gls":"38","p_gls":"5","p_att":"5","crd_y":"86","crd_r":"1","xG":"43.2","npxG":"39.3","xAG":"30.0","prgC":"572","prgP":"1340","gls_per_game":"1.13","ast_per_game":"0.68","np_gls_per_game":"1.00","xG_per_game":"1.14","xAG_per_game":"0.79","npxG_per_game":"1.03"},{"squad":"Valladolid","num_players":"38","age":"25.6","poss":"42.8","gls":"26","ast":"15","np_gls":"21","p_gls":"5","p_att":"5","crd_y":"91","crd_r":"5","xG":"34.6","npxG":"30.7","xAG":"25.7","prgC":"476","prgP":"991","gls_per_game":"0.68","ast_per_game":"0.39","np_gls_per_game":"0.55","xG_per_game":"0.91","xAG_per_game":"0.68","npxG_per_game":"0.81"},{"squad":"Villarreal","num_players":"31","age":"26.7","poss":"47.6","gls":"69","ast":"51","np_gls":"64","p_gls":"5","p_att":"7","crd_y":"96","crd_r":"4","xG":"64.8","npxG":"59.1","xAG":"49.7","prgC":"693","prgP":"1522","gls_per_game":"1.82","ast_per_game":"1.34","np_gls_per_game":"1.68","xG_per_game":"1.71","xAG_per_game":"1.31","npxG_per_game":"1.56"}]
